import re


def clean_sql(sql):
    """
    Clean SQL generated by the LLM and extract
    the actual PostgreSQL SELECT statement.
    """

    sql = sql.strip()

    # Remove markdown code fences
    sql = re.sub(r"```sql", "", sql, flags=re.IGNORECASE)
    sql = sql.replace("```", "")

    # Remove common LLM prefixes
    prefixes = [
        "SQL query:",
        "SQL Query:",
        "sql query:",
        "SQL:",
        "sql:",
        "SELECT query:",
        "Select query:",
        "select query:"
    ]

    for prefix in prefixes:
        sql = sql.replace(prefix, "")

    sql = sql.strip()

    # Find all SELECT positions
    matches = list(
        re.finditer(r"\bSELECT\b", sql, re.IGNORECASE)
    )

    # If multiple SELECT statements exist,
    # use the last one. This handles responses such as:
    # "SELECT query: SELECT current FROM ..."
    if matches:
        sql = sql[matches[-1].start():]

    # Remove everything after the first semicolon
    if ";" in sql:
        sql = sql.split(";", 1)[0] + ";"

    return sql.strip()


def validate_sql(sql):

    sql_lower = sql.lower().strip()

    # Only SELECT queries are allowed
    if not sql_lower.startswith("select"):
        raise ValueError(
            "Only SELECT queries are allowed."
        )

    # Query must use our table
    if "power_measurements" not in sql_lower:
        raise ValueError(
            "Query must use the power_measurements table."
        )

    # Block dangerous SQL operations
    blocked_keywords = [
        "insert",
        "update",
        "delete",
        "drop",
        "alter",
        "truncate",
        "create",
        "grant",
        "revoke",
        "execute"
    ]

    for keyword in blocked_keywords:

        if re.search(
            rf"\b{keyword}\b",
            sql_lower
        ):
            raise ValueError(
                f"Blocked SQL operation: {keyword}"
            )

    return True
