import re


# ============================================================
# ALLOWED TABLE
# ============================================================

ALLOWED_TABLE = "power_measurements"


# ============================================================
# CLEAN SQL
# ============================================================

def clean_sql(sql):
    """
    Clean SQL generated by the local LLM.

    Handles:
    - Markdown code fences
    - SQL: prefixes
    - Explanatory text before SELECT
    - Trailing semicolons
    """

    if not sql:
        raise ValueError(
            "The AI did not generate any SQL."
        )

    sql = sql.strip()

    # --------------------------------------------------------
    # Remove markdown code fences
    # --------------------------------------------------------

    sql = re.sub(
        r"```sql",
        "",
        sql,
        flags=re.IGNORECASE
    )

    sql = re.sub(
        r"```",
        "",
        sql
    )

    sql = sql.strip()

    # --------------------------------------------------------
    # Remove common LLM prefixes
    # --------------------------------------------------------

    prefixes = [
        "SQL:",
        "QUERY:",
        "GENERATED SQL:",
        "SQL QUERY:",
        "ANSWER:"
    ]

    for prefix in prefixes:

        if sql.upper().startswith(prefix):

            sql = sql[len(prefix):].strip()

    # --------------------------------------------------------
    # Find SELECT statement
    #
    # Sometimes the LLM adds explanation before SQL.
    # Example:
    #
    # Here is the query:
    # SELECT AVG(voltage)
    # FROM power_measurements;
    # --------------------------------------------------------

    select_match = re.search(
        r"\bSELECT\b",
        sql,
        re.IGNORECASE
    )

    if not select_match:

        raise ValueError(
            "The AI response does not contain a valid SELECT query."
        )

    # Remove everything before SELECT

    sql = sql[select_match.start():].strip()

    # --------------------------------------------------------
    # Remove trailing markdown/code fence
    # --------------------------------------------------------

    sql = sql.replace("```", "").strip()

    # --------------------------------------------------------
    # Remove ONE trailing semicolon
    # --------------------------------------------------------

    sql = sql.rstrip(";").strip()

    return sql


# ============================================================
# VALIDATE SQL
# ============================================================

def validate_sql(sql):
    """
    Validate generated SQL before execution.
    """

    if not sql:

        raise ValueError(
            "SQL validation failed: empty query."
        )

    # --------------------------------------------------------
    # Must start with SELECT
    # --------------------------------------------------------

    if not re.match(
        r"^\s*SELECT\b",
        sql,
        re.IGNORECASE
    ):

        raise ValueError(
            "Only SELECT queries are allowed."
        )

    # --------------------------------------------------------
    # Prevent multiple SQL statements
    # --------------------------------------------------------

    if ";" in sql:

        raise ValueError(
            "Multiple SQL statements are not allowed."
        )

    # --------------------------------------------------------
    # Block dangerous SQL commands
    # --------------------------------------------------------

    forbidden_commands = [
        "INSERT",
        "UPDATE",
        "DELETE",
        "DROP",
        "ALTER",
        "TRUNCATE",
        "CREATE",
        "GRANT",
        "REVOKE"
    ]

    sql_upper = sql.upper()

    for command in forbidden_commands:

        if re.search(
            rf"\b{command}\b",
            sql_upper
        ):

            raise ValueError(
                f"SQL command '{command}' is not allowed."
            )

    # --------------------------------------------------------
    # Require project table
    # --------------------------------------------------------

    if not re.search(
        rf"\b{ALLOWED_TABLE}\b",
        sql,
        re.IGNORECASE
    ):

        raise ValueError(
            f"Query must use the '{ALLOWED_TABLE}' table."
        )

    # --------------------------------------------------------
    # Require FROM clause
    # --------------------------------------------------------

    if not re.search(
        r"\bFROM\b",
        sql,
        re.IGNORECASE
    ):

        raise ValueError(
            "SQL validation failed: FROM clause is missing."
        )

    return True
